### ISSUE TITLE
Please take out the empty curly bracket!

### ISSUE THREAD

**Issue by UlitmateTesa** [Fifteen15Studios/MMM-AutoDimmer#1]
Hello!

First of all: Thank you for your work on this module! We are very happy that we can use it.

One simple note: Could you rework the script pictured in the second example? There is an empty curly bracket, which causes the screen to dim for just 1 second and instantly return to full brightness.

I literally sat at this problem for 20 minutes...

Greetings

**Comment by Fifteen15Studios** [comment]
I am not sure what you are referring to. I am definitely looking into some issues with the module, which were introduced when I introduced multiple schedules, but I'm not sure what you think is leading to the problem you're referring to.

**Comment by UlitmateTesa** [comment]
Hello again.

I want to apologize. I did not see that the curly bracket I was referring to, was just to give an Example...

So there is no problem left. :)

Maybe next time I should think before I act...

Best regards

**Comment by Fifteen15Studios** [comment]
I've reverted the code back to the point where it only handled 1 schedule, until I can fix all of the issues with having multiple schedules.
