### ISSUE TITLE
Module does not dim on the weekend?

### ISSUE THREAD

**Issue by Moritz272** [Fifteen15Studios/MMM-AutoDimmer#2]
Hello.
I want to use this module to dim the Magic Mirror at night and on Saturday and Sunday. 

The module perfectly dims the screen at my chosen time at 6pm and brightens the screen again in the morning at 6am.
But if I want the screen to stay dimmed on the weekend it does not work. 
On the two days it also dims at 6pm and brightens at 6am but since I did not put Saturday and Sunday in the "days" I do not not know whats the problem of the script.

{
    module: 'MMM-AutoDimmer',
    position: 'fullscreen_above',
    header: '',
    // Don't change anything above this line
    config: {
      schedules: [
        {
          days: ["Monday","Tuesday","Wednesday","Thursday","Friday"],
          dimTime: 600,
          brightTime: 1800,
          maxDim: 1.0,
		  transitionDuration: 1000,
        }
      ]
    }
  },

I hope you can help.

Best regards
Moritz

**Comment by Fifteen15Studios** [comment]
I've reverted the code back to the point where it only handled 1 schedule, until I can fix all of the issues with having multiple schedules.
