### ISSUE TITLE
MaxDim numbers

### ISSUE THREAD

**Issue by Tragus52** [Fifteen15Studios/MMM-AutoDimmer#3]
Have set MaxDim number to 1.0, expect the screen to be black as stated in Readme file, however with this setting screen is still transparent.

**Comment by Fifteen15Studios** [comment]
What does the rest of the config block look like? I have a schedule with it set to 1 and it works as expected.

**Comment by Tragus52** [comment]
Brighttime: 700,
DimTime: 2200,
TransitionDuration: 10 * 60 * 1000,
TransitionSteps: 20,

**Comment by Fifteen15Studios** [comment]
Are you using the latest version? If so, did you modify your config to match the new format? You must have a schedule in the latest version.
