### ISSUE TITLE
Changing parameters with Config file takes full day to take effect

### ISSUE THREAD

**Issue by Nneuland** [Fifteen15Studios/MMM-AutoDimmer#4]
Not sure this should be considered an issue.  But I noticed if changes are made during the dimming time, the mirror dimming doesn't reflect the changes until the next day.  Just something small I noticed.  Happy to clarify if needed.

**Comment by Fifteen15Studios** [comment]
If you're changing the config file, you should be reloading the MM to make the config changes take effect. If you're not doing that, I don't know how you expect it to know you changed the config. If you are doing that, I'm not sure what you mean and need clarification as to your exact process.

**Comment by Nneuland** [comment]
Yes.  I’ve been attempting to set up a long dim time.  Starting at 7pm and
reaching the max dim after 4 hours of dimming.

After I modify the max dim parameter to suit my needs, and restarting MM,
the mirror is exhibiting an incredibly dark dim.

I’ve noticed my adjustments go into effect, but not until I allow a full
day to pass and let the module “reset” the next day.

The module is working beautifully, but I’ve noticed this strange accordance
is all.

I should also note that I’m using this module in conjunction with
 Mmm-remote control.  Not sure if that is having any influence

**Comment by Fifteen15Studios** [comment]
If you start it during the schedule, it will start fully dim. So in your case, if you start your MM between 7pm and whenever the end of your schedule is, it will start fully dimmed. If, instead, you were to start it at 6:59, it will start bright and slowly dim. 

I'm sure that with enough code I could start it partially dim, based on how far into the transition time you are, but that would be a lot of work for a very edge case.

**Comment by Nneuland** [comment]
Yeah.  I figured.  Thank you for your time!

**Comment by Fifteen15Studios** [comment]
This will be fixed in the next version. I just got it working, as I needed to do this for some other features I'm working on. Not sure when the next version will be released, but it should be within the next week or 2.

**Comment by Fifteen15Studios** [comment]
Also, it will work during the "brightening" time too (during the transition from dim to bright)

**Comment by Fifteen15Studios** [comment]
The new release properly handles this situation
