### ISSUE TITLE
Not fully dimming

### ISSUE THREAD

**Issue by Plainbroke** [Fifteen15Studios/MMM-AutoDimmer#5]
@Fifteen15Studios 
I have maxDim set to 1.0 and it does not go fully dark as I expected.  Actually, there seems to be no difference between default and the maxDim set to 1.0 
`{
	module: "MMM-AutoDimmer",
	position: "fullscreen_above",
	header: "",
	config: {
	maxDim: 1.0,
		schedules: [{
			dimTime: 1450,
			brightTime: 700
					}] // Uses all default values
			}
},`

Do I have something out of order or not correct at all?

**Comment by Fifteen15Studios** [comment]
The maxDim should be inside of the schedule. The only thing that goes into the main config is the schedules

**Comment by Fifteen15Studios** [comment]
> Ok that was what I needed clarified the readme doesn't really specify that.  Maybe you could update the readme to show where to put the options..

It does explain it in the configuration options
