### ISSUE TITLE
Updated code dimmed on startup

### ISSUE THREAD

**Issue by howest99** [Fifteen15Studios/MMM-AutoDimmer#6]
I updated MMM-AutoDimmer this morning.  When I start MagicMirror, it is dimmed, even though it is during the bright time (currently 10am) .  I reverted to the default config with no effect.

**Comment by Fifteen15Studios** [comment]
I just pushed another update. Should be fixed in the latest version.

**Comment by howest99** [comment]
It works!  Thank you so much
